### PR TITLE
Update druid-powered.md

### PR DESCRIPTION
**Pull request by saeedtabrizi**
Add deema.agency to powered.md file .

### CODE REVIEW

**Comment by saeedtabrizi** [comment]
Hi @glasser , @junrao , @vogievetsky 
Is there any plan or update for merge request  ?

**Review by jelenazanko — CHANGES_REQUESTED** [review]
Hello @saeedtabrizi,
1. Please update spelling of "challanging" to "challenging"
2. Can you please edit "realtime-time metrics" in the last part to "realtime metrics"?

Thank you!

**Comment by saeedtabrizi** [comment]
Hello @jelenazanko 
Thanks for your review and all issue has been fixed .

**Comment by saeedtabrizi** [comment]
Hi @jelenazanko ,
Is there any update ?

**Comment by jelenazanko** [comment]
Apologies @saeedtabrizi, I no longer work on this project. @petermarshallio can you please assist in getting Deema Agency's entry added to Powered By?

**Comment by petermarshallio** [comment]
Hi @saeedtabrizi ! Let me ping one of the committers and see if I can pull this together.

**Pull request merged**
