### PR TITLE
Updating and removing unnecessary white spaces on use case page

### PR DESCRIPTION
**Pull request by 2bethere**
Thanks @rohan-joshi for reporting
Removing the white spaces on use case page:
image

Also removes the large header as they are redundant
image

### CODE REVIEW

**Review by 317brian — APPROVED** [review]
I built it locally, and while this doesn't retain the original zig zag pattern the old site had, it seems like a good compromise instead of spending time figuring out why the font awesome icons will render in `yarn start` previews but not the actual build output

image

How do you feel about this change @ektravel ?

**Comment by ektravel** [comment]
In my opinion, we should completely remove the icons as they make use case paragraphs appear as bullet points. Additionally, could we modify the headings for the use cases to H3? They appear at the same level as 'Common use case examples,' and I presume the intention is to have them nested under the 'Common use case examples' H2.

**Comment by 2bethere** [comment]
Can do, will modify.

**Comment by 2bethere** [comment]
Looks like this now:
image

**Review by ektravel — APPROVED** [review]
Thank you for making these changes!

**Pull request merged**
