### PR TITLE
Update the preferred channel to get community help

### PR DESCRIPTION
**Pull request by abhishekagarwal87**

### CODE REVIEW

**Comment by jihoonson** [comment]
Same comment here. Promoting Slack sounds good, but I don't want to depromote the user group. Users should file their issue there first because it's indexed by search engines.

**Comment by petermarshallio** [comment]
Please see also the related PR for the addition of Druid Forum (if that's cool?)
https://github.com/apache/druid-website-src/pull/282

**Comment by fjy** [comment]
@abhishekagarwal87 can you fix conflicts?

**Comment by abhishekagarwal87** [comment]
@fjy - I am holding off this PR since the community is talking about creating a different more accessible slack channel. I would like to promote the new slack channel itself.

**Comment by vogievetsky** [comment]
this had been addressed in other ways

**Pull request closed without merging**
